# Use Node.js Alpine image for smaller size
FROM node:20.7.0-alpine

# Set working directory
WORKDIR /app

# Install build tools
RUN apk add --no-cache python3 make g++

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy environment variables
COPY .env ./

# Copy all source code
COPY . .

RUN npx prisma generate

RUN npm run initDB

# Expose the API port
EXPOSE 3001

# Start the application
CMD ["npm", "start"]