# Use Node.js Alpine image for smaller size
FROM node:20.7.0-alpine

# Set working directory
WORKDIR /app

RUN apk add --no-cache postgresql-client


# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy environment variables
COPY .env ./

# Copy all source code
COPY . .

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

# Expose the API port
EXPOSE 3001

ENTRYPOINT [ "entrypoint.sh" ]

# Start the application
CMD ["npm", "start"]